version: '3.6'

services:
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ".:/var/www/html"
    ports:
      - '80:80'
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=testLifemart
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - default